#!/usr/bin/env bash
# This init script starts, stops or restarts manage_my_process
pid_file="/var/run/my_process.pid"

start() {
	./manage_my_process &
	echo "$!" > "$pid_file"
}

stop() {
	kill "$(cat "$pid_file")"
	rm -f "$pid_file"
}

case "$1" in
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
